---
- include_tasks:                '../tasks/install_files.yml'
- include_tasks:                '../tasks/apt_update.yml'
  when:                         install_files_result.changed
- include_tasks:                '../tasks/install_packages.yml'
